name: Publish to Chocolatey

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Version name (e.g., 0.2.7)'
        required: true

concurrency:
  group: choco-${{ inputs.version_name }}
  cancel-in-progress: false

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Preflight | Check release + asset
        shell: pwsh
        run: |
          $tagUrl = "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ inputs.version_name }}"
          try { Invoke-RestMethod $tagUrl | Out-Null } catch { throw "Release tag '${{ inputs.version_name }}' not found." }

          $assetUrl = "https://github.com/${{ github.repository }}/releases/download/${{ inputs.version_name }}/imagot.exe"
          try { Invoke-WebRequest $assetUrl -Method Head -UseBasicParsing | Out-Null } catch { throw "Release asset imagot.exe not found at $assetUrl" }

      - name: Preflight | Check secret
        shell: pwsh
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        run: |
          if (-not $env:CHOCO_API_KEY) { throw "Missing secret CHOCO_API_KEY" }

      - name: Download Windows exe
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path .\choco-package | Out-Null
          $url = "https://github.com/${{ github.repository }}/releases/download/${{ inputs.version_name }}/imagot.exe"
          Invoke-WebRequest $url -OutFile ".\choco-package\imagot.exe"

      - name: Generate checksum
        shell: pwsh
        run: |
          $hash = (Get-FileHash -Path ".\choco-package\imagot.exe" -Algorithm SHA256).Hash.ToLower()
          "@($hash)  imagot.exe" | Out-File -FilePath ".\choco-package\SHA256SUMS.txt" -Encoding utf8
          Write-Host "SHA256: $hash"

      - name: Setup Chocolatey
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: -v

      - name: Update nuspec version
        shell: pwsh
        run: |
          $p = ".\chocolatey\imagot.nuspec"
          (Get-Content $p) -replace "<version>.*</version>", "<version>${{ inputs.version_name }}</version>" | Set-Content $p

      - name: Update install script URL + checksum
        shell: pwsh
        run: |
          $checksumLine = Get-Content ".\choco-package\SHA256SUMS.txt" | Select-Object -First 1
          $hash = ($checksumLine -split '\s+')[0]
          $install = ".\chocolatey\tools\chocolateyinstall.ps1"
          $c = Get-Content $install
          $c = $c -replace "url\s*=\s*'.*'", "url = 'https://github.com/${{ github.repository }}/releases/download/${{ inputs.version_name }}/imagot.exe'"
          $c = $c -replace "checksum\s*=\s*'.*'", "checksum = '$hash'"
          $c | Set-Content $install
          Write-Host "Updated chocolateyinstall.ps1"

      - name: Pack and push
        shell: pwsh
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        run: |
          choco pack .\chocolatey\imagot.nuspec
          choco push imagot.${{ inputs.version_name }}.nupkg --source https://push.chocolatey.org/ --api-key $env:CHOCO_API_KEY
