name: Publish to WinGet

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Version name (e.g., 0.2.7)'
        required: true

concurrency:
  group: winget-${{ inputs.version_name }}
  cancel-in-progress: false

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Preflight | Check release tag
        shell: pwsh
        run: |
          $tagUrl = "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ inputs.version_name }}"
          try { Invoke-RestMethod $tagUrl | Out-Null } catch { throw "Release tag '${{ inputs.version_name }}' not found." }

      - name: Preflight | Check secret
        shell: pwsh
        env:
          WINGET_TOKEN: ${{ secrets.WINGET_TOKEN }}
        run: |
          if (-not $env:WINGET_TOKEN) { throw "Missing secret WINGET_TOKEN" }

      - name: Submit to WinGet
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: MLMGames.Imagot
          version: ${{ inputs.version_name }}
          release-tag: ${{ inputs.version_name }}
          token: ${{ secrets.WINGET_TOKEN }}
